---
title: "Preparation of Shalek SCESet for phenotime"
author: "Kieran Campbell"
date: "March 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE)

library(scater)
library(tidyverse)
library(magrittr)
library(matrixStats)
library(biomaRt)
library(curl)

scale_vec <- function(x) (x - mean(x)) / sd(x)
```


```{r data-prep, cache = FALSE}
sce <- readRDS("../../data/shalek/sce_shalek.rds")

dvar <- data_frame(var_exprs = matrixStats::rowVars(exprs(sce)),
                   mean_exprs = rowMeans(exprs(sce)))
```


```{r select-high-variance}
to_use <- dvar$var_exprs > 2

print(paste("Retaining", sum(to_use), "genes"))

sc <- sce[to_use, ]
```

Then choose covariates:

```{r choose-cov}
sc <- sc[, sc$stimulant != "PIC"]
```

Add in covariate:

```{r add-in-covariate}
sc$x <- scale_vec( sc$stimulant == "LPS" )
```

Regress out technical effect:

```{r regress-out-technical}
pc1 <- prcomp(t(exprs(sc)), scale = TRUE)$x[,1]
sc$pc1 <- pc1
m <- model.matrix(~ pc1)
sc <- normaliseExprs(sc, design = m)
exprs(sc) <- norm_exprs(sc)
```



And save the result:

```{r save-tumour-gene}
saveRDS(sc, file = "../../data/shalek/sce_shalek_clvm.rds")
```