---
title: "Preparation of COAD SCESet for phenotime"
author: "Kieran Campbell"
date: "9 October 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE)

library(scater)
library(tidyverse)
library(magrittr)
library(matrixStats)
library(biomaRt)
library(curl)

scale_vec <- function(x) (x - mean(x)) / sd(x)
```


```{r data-prep, cache = FALSE}
sce <- readRDS("../../data/COAD/sce_coad.rds")
sampleNames(sce) <- sampleNames(assayData(sce))
sce <- sce[matrixStats::rowVars(tpm(sce)) > 0, ]
is_exprs(sce) <- tpm(sce) > 0
sce <- calculateQCMetrics(sce)

hgnc_symbols <- sapply(strsplit(featureNames(sce), "_"), `[`, 2)

dvar <- data_frame(var_exprs = matrixStats::rowVars(exprs(sce)),
                   hgnc_symbols)

fData(sce)$var_exprs <- matrixStats::rowVars(exprs(sce))
fData(sce)$hgnc_symbols <- hgnc_symbols

## group factors to avoid low frequency ones
gt_table <- table(fData(sce)$gene_type)
new_gt_names <- names(gt_table)
new_gt_names[gt_table < 50] <- "other"
fData(sce)$short_gene_type <- plyr::mapvalues(fData(sce)$gene_type,
                                             from = names(gt_table),
                                             to = new_gt_names)
sce <- sce[fData(sce)$n_cells_exprs > 0, ]
```

# Strip out technical effects

```{r pca-all, cache = FALSE}
sce <- plotPCA(sce, ncomponents = 3, colour_by = "short_plate",
               return_SCESet = TRUE)
pca_plot <- last_plot()
saveRDS(pca_plot, file = "../../figs/coad/pca.rds")
```

We see technically distinct clusters of cells. We want to target the largest, so strip out those that aren't there:

```{r subset-sceset, cache = FALSE}
sc <- sce[, redDim(sce)[,1] < 0 & redDim(sce)[,3] > -10]

## After subsetting, re-calculate QC metrics
sc <- calculateQCMetrics(sc)
```

And let's plot this and colour by tumour / normal:

```{r sc-pca}
plotPCA(sc, colour_by = "sample_type", ncomponents = 3)
```


Data preparation:

```{r phenotime-data-preparation}
sc_tumour <- sc[, sc$sample_type != "normal"]
```

Construct a gene level SCESet:

```{r to-gene-level}
sc_tumour_gene <- summariseExprsAcrossFeatures(sc_tumour,
                                               summarise_by = "ensembl_gene_id")
```

Download relevant data:

```{r download-data}
fData(sc_tumour_gene)$ensembl_gene_id <- fData(sc_tumour_gene)$exprs_collapsed_to

fData(sc_tumour_gene)$ensembl_gene_id <- gsub(fData(sc_tumour_gene)$ensembl_gene_id, pattern = "\\.[0-9]+", replacement = "")

ensembl_gene_id <- fData(sc_tumour_gene)$ensembl_gene_id

annotation_file <- "../../data/gene_annotations.csv"

if(file.exists(annotation_file)) { # do nothing
  gene_annos <- read_csv(annotation_file)
} else if(has_internet()) {
  mart <- useMart(biomart = 'ensembl', 
          dataset = 'hsapiens_gene_ensembl')
  gene_annos <- getBM(mart = mart, 
                         filters = "ensembl_gene_id",
                         attributes = c("ensembl_gene_id",
                                        "hgnc_symbol",
                                        "transcript_biotype"),
              values = ensembl_gene_id)

  write_csv(gene_annos, annotation_file)
} else {
  stop("Annotation file missing and ")
}

mm <- match(ensembl_gene_id, gene_annos$ensembl_gene_id)
non_na_mm <- which(!is.na(mm))
mm <- mm[non_na_mm]

gene_annos <- gene_annos[mm, ]
sc_tumour_gene <- sc_tumour_gene[non_na_mm, ]


## Now add them in to the fData
stopifnot(all.equal(fData(sc_tumour_gene)$ensembl_gene_id,
                    gene_annos$ensembl_gene_id))

for(nn in names(gene_annos)) {
  fData(sc_tumour_gene)[[nn]] <- gene_annos[[nn]]
}

featureNames(sc_tumour_gene) <- paste0(fData(sc_tumour_gene)$hgnc_symbol, "_", fData(sc_tumour_gene)$ensembl_gene_id)

```

```{r add-meta}
pseudogenes <- grepl("pseudogene", fData(sc_tumour_gene)$transcript_biotype)
not_pseudogene <- which(!pseudogenes)

sc_tumour_gene <- sc_tumour_gene[not_pseudogene, ]
sc_tumour_gene <- calculateQCMetrics(sc_tumour_gene)
```

Add in MMR genes:

```{r add-mmr-gene}
## Add in MMR genes

mmr_genes <-  c("MLH1", "MLH3", "MSH2", "MSH3", "MSH6", "^PMS1_", "^PMS2_",
               "PCNA_", "^RPA1", "^RPA2", "^RPA3", "HMGB1", "RFC",  "^POLD1", "POLD2", 
               "POLD3", "POLD4", "^LIG1")

gene_inds <- unlist(sapply(mmr_genes, grep, featureNames(sc_tumour_gene)))

is_mmr <- rep(FALSE, nrow(sc_tumour_gene))
is_mmr[gene_inds] <- TRUE
fData(sc_tumour_gene)$is_mmr <- is_mmr
```

Select high variance genes:

```{r select-high-variance}
var_exprs <- matrixStats::rowVars(exprs(sc_tumour_gene))

to_use <- var_exprs > 0.5 | fData(sc_tumour_gene)$is_mmr

print(paste("Retaining", sum(to_use), "genes"))
print(paste(sum(fData(sc_tumour_gene)$is_mmr), "mmr genes"))

sce <- sc_tumour_gene[to_use, ]
```

Add in covariate:

```{r add-in-covariate}
sce$x <- scale_vec( 1 * (sce$msi_status == "msi-h") )
```

And save the result:

```{r save-tumour-gene}
saveRDS(sce, file = "../../data/COAD/sce_coad_clvm.rds")
```